name : CI

on: 
  push:
    branches:
      - main
  
  pull_request:


jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest' , 'windows-latest' , 'macos-latest']
        version: ['3.9' , '3.10']
    steps:
      - name: Code Checkout 
        uses: actions/checkout@v3   # for pasting code on runner 

      - name: Setup Python 
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.version }}

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 

      - name: run flake8 
        run:
          flake8 app.py
  
  testings:
    runs-on: 'ubuntu-latest'

    steps: 
      - name: code checkout 
        uses: actions/checkout
      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: run unit test 
        run: |
          python -m unittest discover 

        


# this is the simple ci workflow to check linting errors 


