name : CI

on: push 

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout 
        uses: actions/checkout@v3   # for pasting code on runner 

      - name: Setup Python 
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 

      - name: run flake8 
        run:
          flake8 app.py


# this is the simple ci workflow to check linting errors 


